import { TranslateSection } from "@/types/homepageDictionnary";

const TranslateSection0: TranslateSection = {
  fr: [
    "Votre review Honkai : Star Rail",
    "C'est quoi Review HSR ?",
    "Un site d'aide pour améliorer facilement vos personnages.",
    "Des conseils clairs et adaptés pour une utilisation en toute simplicité.",
    `Mettez vos personnages du jeu en vitrine. [b](cf. vidéo de la page)[/b]`,
    `Entrez votre UID sur le site et cliquez sur "Rechercher".[b] Si vous venez de modifier votre vitrine en jeu, patientez 10 minutes [/b]pour que la synchronisation soit bien effectuée.`,
    `Si un personnage possède plusieurs façons d'être équipé / joué, il faudra sélectionner le build correspondant à votre utilisation.`,
    "Le moindre élément qui ne convient pas sera noté en ",
    "rouge",
    " et des recommandations seront faites pour vous aider.",
    "Les éléments suivants sont analysés :",
    `Le cône.`,
    `Les ensembles de reliques et ornements.`,
    `Les statistiques principales de vos pièces.`,
    `Vos statistiques finales.`,
    `La pertinence de vos pièces avec un système de notation (de D à SSS).`,
    "Sélectionnez ou survolez les éléments en ",
    " pour voir une recommandation accessible pour tous.",
    "Si votre personnage n'a aucun élément en rouge alors il est bien équipé",
    ", libre à vous d'essayer d'améliorer la pièce avec la notation la plus faible ou de passer au personnage suivant !",
    "Sélectionnez vos personnages en vitrine",
  ],
  en: [
    "Your Honkai Star Rail review",
    "What is HSR review?",
    "A website to help your build for characters easily",
    "Some clear and relevant advices for a simple use.",
    `Put your characters for show. [b](see video)[/b]`,
    `Type your UID on the site and click on "Search". [b]If you just modified your showing panel, please wait about 10 minutes[/b] so the synchronizing could be complete.`,
    `If one of your characters can have 2 builds or more, you will have to select the one who shall meet your use.`,
    "Every element who shall not meet expectations will be shown in",
    " red ",
    "and recommandations are done to help you.",
    "Those elements are analysed :",
    `Lightcone`,
    `Relics and ornaments sets`,
    `Main stats of all of your pieces`,
    `Your final stats.`,
    `The efficiency of your relics rated from D to SSS`,
    "Select or go over the elements to",
    "to see an easy-to-get recommandation for all players.",
    "If your character doesnt have a red element then he's well-equiped,",
    "you're free to improve its lowest ranked piece or to take care of the next character",
    "Select your characters on showing panel",
  ],
};

const TranslateSection1: TranslateSection = {
  fr: [
    "Analyse des Recommandations",
    "Le site analyse des personnages terminés, c'est à dire avec le niveau, le cône, les traces et les reliques / ornements améliorés. Prenez donc en considération qu'une relique sera par exemple mal notée si elle n'est pas montée.",
    "Les statistiques recommandées ",
    "permettent d'évaluer le besoin d'un personnage et votre objectif à dépasser.",
    "Bien évidement si vous offrez de la vitesse ou des gains d'actions avec des personnages tels que Sparkle ou Bronya, alors [b]la recommandation de vitesse ne sera pas la même[/b] (à vous d'ajuster / réduire)",
    "Les recommandations sont faites pour posséder des personnages [b][color=#108f10]versatiles[/color][/b] et [b][color=#108f10]équilibrés[/color][/b].",
    "Les Notes et Objectifs",
    "Le système de notation de Reliques et Ornements prend en compte les besoins du personnage. Les statistiques les plus utiles amélioreront significativement la notation (chaque statistique a son coef. en fonction du personnage), les valeurs obtenues, le nombre d'augmentations de statistiques (4 ou 5) ainsi que la statistique principale. [b]Les statistiques jugées totalement inutiles n'amélioreront pas la notation[/b] :",
    "Une notation inférieure (de [b][color=#FF4B4B] D [/color][/b] à [b][color=#FF4B4B] B+[/color][/b]) signifie qu'il est fortement recommandé de changer la pièce correspondante.",
    "Obtenir une note de [b][color=#04576f]A[/color][/b] ou [b][color=#04576f]A+[/color][/b] est la moyenne à atteindre si possible partout.",
    "Une notation supérieur (de [b][color=#108f10]S[/color][/b] à [b][color=#108f10]SSS[/color][/b]) confirme que la pièce est très bien et qu'il n'y a pas besoin de perdre du temps à l'améliorer (sauf si vous souhaitez perfectionner votre personnage).",
  ],
  en: [
    "Analysis of Recommendations",
    "The site analyzes completed characters (level, cone, traces, and relics/ornaments upgraded). Therefore, please consider that a relic, for example, will be poorly rated if it is not upgraded.",
    "Recommended statistics",
    "The recommended statistics allow evaluating the needs of a character and your goal to surpass.",
    "Of course, if you provide speed or action gains with characters like Sparkle or Bronya, then [b]the speed recommendation will not be the same[/b] (you should adjust/reduce it).",
    "Recommendations are made for owning [b][color=#108f10]versatile[/color][/b] and [b][color=#108f10]balanced[/color][/b] characters.",
    "Notes and Goals",
    "The Relics and Ornaments rating system takes into account the character's needs. The most useful statistics will significantly improve the rating (each statistic has its coefficient depending on the character), the obtained values, the number of statistic increases (4 or 5), and the main statistic. [b]Statistics deemed completely useless will not improve the rating[/b] :",
    "A lower rating (from [b][color=#FF4B4B]D[/color][/b] to [b][color=#FF4B4B]B+[/color][/b]) means that it is strongly recommended to change the corresponding piece.",
    "Achieving a rating of [b][color=#04576f]A[/color][/b] or [b][color=#04576f]A+[/color][/b] is the average to aim for if possible everywhere.",
    "A higher rating (from [b][color=#108f10]S[/color][/b] to [b][color=#108f10]SSS[/color][/b]) confirms that the piece is very good, and there is no need to waste time improving it (unless you want to perfect your character).",
  ],
};

const TranslateSection1Array: TranslateSection = {
  fr: ["A ou A+", "Genial", "A améliorer"],
  en: ["A or A+", "Awesome", "Needs improvement"],
};

const TranslateSection2: TranslateSection = {
  fr: [
    "Codes actifs",
    "Lien copié",
    "Dépenser moins sur HSR tout en soutenant le site !",
    "En utilisant ce lien Lootbar pour vos achats, vous soutiendrez énormément !",
    "https://lootbar.gg/fr/top-up/honkai-star-rail?utm_source=Azano",
    "Achetez sur le site ",
    "pour obtenir de [b][color=#00ff00]10%[/color][/b] à [b][color=#00ff00]20%[/color][/b] de réduction sur le pack à 100€.",
    "Rapide et sécurisé avec Razer Gold",
    "Réception instantanée en jeu !",
    "(partenaire Hoyoverse)",
    "Votre UID suffit, pas besoin de vos identifiants personnels.",
    "Au besoin, passez sur le live Twitch d'",
    " pour plus d'informations.",
  ],
  en: [
    "Active Codes",
    "Link Copied",
    "Spend less on HSR while supporting the site!",
    "By using this Lootbar link for your purchases, you will greatly support us!",
    "https://lootbar.gg/top-up/honkai-star-rail?utm_source=Azano",
    "Buy on the site ",
    "to get [b][color=#00ff00]10%[/color][/b] to [b][color=#00ff00]20%[/color][/b] discount on the €100 pack.",
    "Fast and secure with Razer Gold",
    "Instant in-game delivery!",
    "(Hoyoverse partner)",
    "Your UID is enough, no need for your personal credentials.",
    "If needed, visit the Twitch live stream of",
    " for more information.",
  ],
};

export {
  TranslateSection0,
  TranslateSection1,
  TranslateSection2,
  TranslateSection1Array,
};
