import { TranslateSection } from "@/types/homepageDictionnary";

const StatsTranslate: TranslateSection = {
  fr: [
    "Mis à jour le",
    "à",
    "Stats sur",
    "comptes",
    "Statistiques attribuées par les joueurs",
    "Moyenne",
    "PV",
    "ATQ",
    "DEF",
    "VIT",
    "Chances Crit.",
    "DGT Crit.",
    "Effet de rupture",
    "App. des effets",
    "RÉS des effets",
    "Régen. d'énergie",
    "Statistiques priorisées par les joueurs",
    "Top 5 Reliques + Ornements",
    "Top 5 Cones de lumière",
  ],
  en: [
    "Updated at",
    "at",
    "Stats on",
    "accounts",
    "Player Assigned Stats",
    "Average",
    "HP",
    "ATK",
    "DEF",
    "SPD",
    "Crit. Rate",
    "Crit. Damage",
    "Break Effect",
    "Effect Hit",
    "Effect RES",
    "Energy Regen",
    "Player Prioritized Stats",
    "Top 5 Relics + Ornaments",
    "Top 5 Light Cones",
  ],
};

export { StatsTranslate };
