import { TranslateSection } from "@/types/homepageDictionnary";

const StatsTranslate: TranslateSection = {
  fr: [
    "Mis à jour le",
    "à",
    "Stats sur",
    "comptes",
    "Statistiques attribuées par les joueurs",
    "Moyenne",
    "PV",
    "ATQ",
    "DEF",
    "VIT",
    "Chances Crit.",
    "DGT Crit.",
    "Effet de rupture",
    "App. des effets",
    "RÉS des effets",
    "Régén. d'énergie",
    "Statistiques priorisées par les joueurs",
    "Top Reliques",
    "Top Ornements",
    "Top Cones de lumière",
    "Aucune statistiques pour ce personnage T_T",
  ],
  en: [
    "Updated at",
    "at",
    "Stats on",
    "accounts",
    "Player Assigned Stats",
    "Average",
    "HP",
    "ATK",
    "DEF",
    "SPD",
    "Crit. Rate",
    "Crit. Damage",
    "Break Effect",
    "Effect Hit",
    "Effect RES",
    "Energy Regen.",
    "Player Prioritized Stats",
    "Top Relics",
    "Top Ornaments",
    "Top Light Cones",
    "No stats for this character T_T",
  ],
};

export { StatsTranslate };
